# conda
name: venvFinRisk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - pip:
    - pip-tools
    - ipynb==0.5.1
    - pandas
    - numpy
    - orjson
    - mxnet~=1.7 #maxima version compatible con windows. la version de request debe ser maximo 2.19.0 y yfinace debe tener 0.20.0 como minimo.
    - gluonts==0.9.4
    - matplotlib
    - scipy
    - plotly==5.15.0
    - nbformat==5.7.3
  - ipykernel